import type { Metadata } from "next";
import localFont from "next/font/local";
import { Fredoka } from "next/font/google";
import "./globals.css";
import NavbarPrimary from "@/components/navbar-primary";
import AuthProvider from "@/components/providers/auth-provider";
import { FileProvider } from "@/contexts/files-context";

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
  weight: ["300", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fredoka.variable} antialiased`}>
        <AuthProvider>
          <FileProvider>
            <NavbarPrimary />
            {children}
          </FileProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
